build_cloud: byodlinuxappveyor
image: LinuxApu2004

install:

build:
  verbosity: detailed

build_script:
  - ./gradlew --info build

artifacts:
  - path: build/libs/*.jar
    name: AppveyorSpike