image: Ubuntu2004

install:
  - sh: sudo apt-get update
  - sh: sudo apt-get -y install openjdk-16-jdk

build:
  verbosity: detailed

build_script:
  - sh: java -version
  - sh: ls /usr/lib/jvm/
  #- sh: sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0_version/bin/java
  - ./gradlew --info build

artifacts:
  - path: build/libs/*.jar
    name: AppveyorSpike