image: Ubuntu2004

install:
  - sh: sudo apt-get update
  - sh: sudo apt-get install openjdk-16-jdk

build:
  verbosity: detailed

build_script:
  - ./gradlew --info build

artifacts:
  - path: build/libs/*.jar
    name: AppveyorSpike